language: python
python:
    - "3.5"
env:
    - DJANGO=1.10.1
install:
    - pip install django
    - pip install pep8
    - pip install -q -e .
before_script:
    - "pep8 --exclude=migrations --ignore=E501, E225, src"
    - pyflakes -x W src
